# Generated by Django 2.2.1 on 2019-05-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNo', models.CharField(max_length=50)),
                ('allotedSideName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sides.Side')),
                ('driverName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Driver')),
                ('fuelType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Fuel')),
            ],
        ),
    ]
