# Generated by Django 2.2.1 on 2019-05-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sides.Side')),
            ],
        ),
    ]
